/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardSitesRouteRouteImport } from './routes/dashboard/sites/route'
import { Route as DashboardSchedulesRouteRouteImport } from './routes/dashboard/schedules/route'
import { Route as DashboardJobsRouteRouteImport } from './routes/dashboard/jobs/route'
import { Route as DashboardDronesRouteRouteImport } from './routes/dashboard/drones/route'
import { Route as DashboardUiIndexRouteImport } from './routes/dashboard/ui/index'
import { Route as DashboardSitesIndexRouteImport } from './routes/dashboard/sites/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSchedulesIndexRouteImport } from './routes/dashboard/schedules/index'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard/jobs/index'
import { Route as DashboardFormsIndexRouteImport } from './routes/dashboard/forms/index'
import { Route as DashboardDronesIndexRouteImport } from './routes/dashboard/drones/index'
import { Route as DashboardSitesNewRouteImport } from './routes/dashboard/sites/new'
import { Route as DashboardSchedulesNewRouteImport } from './routes/dashboard/schedules/new'
import { Route as DashboardJobsNewRouteImport } from './routes/dashboard/jobs/new'
import { Route as DashboardFormsFormIdRouteImport } from './routes/dashboard/forms/$formId'
import { Route as DashboardDronesNewRouteImport } from './routes/dashboard/drones/new'
import { Route as DashboardSchedulesScheduleIdIndexRouteImport } from './routes/dashboard/schedules/$scheduleId/index'
import { Route as DashboardDronesDroneIdIndexRouteImport } from './routes/dashboard/drones/$droneId/index'
import { Route as DashboardSitesSiteIdEditRouteImport } from './routes/dashboard/sites/$siteId/edit'
import { Route as DashboardSchedulesScheduleIdEditRouteImport } from './routes/dashboard/schedules/$scheduleId/edit'
import { Route as DashboardJobsJobIdEditRouteImport } from './routes/dashboard/jobs/$jobId/edit'
import { Route as DashboardDronesDroneIdEditRouteImport } from './routes/dashboard/drones/$droneId/edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSitesRouteRoute = DashboardSitesRouteRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchedulesRouteRoute = DashboardSchedulesRouteRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsRouteRoute = DashboardJobsRouteRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDronesRouteRoute = DashboardDronesRouteRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardUiIndexRoute = DashboardUiIndexRouteImport.update({
  id: '/ui/',
  path: '/ui/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSitesIndexRoute = DashboardSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSitesRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchedulesIndexRoute = DashboardSchedulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSchedulesRouteRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardJobsRouteRoute,
} as any)
const DashboardFormsIndexRoute = DashboardFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDronesIndexRoute = DashboardDronesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDronesRouteRoute,
} as any)
const DashboardSitesNewRoute = DashboardSitesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardSitesRouteRoute,
} as any)
const DashboardSchedulesNewRoute = DashboardSchedulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardSchedulesRouteRoute,
} as any)
const DashboardJobsNewRoute = DashboardJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardJobsRouteRoute,
} as any)
const DashboardFormsFormIdRoute = DashboardFormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDronesNewRoute = DashboardDronesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardDronesRouteRoute,
} as any)
const DashboardSchedulesScheduleIdIndexRoute =
  DashboardSchedulesScheduleIdIndexRouteImport.update({
    id: '/$scheduleId/',
    path: '/$scheduleId/',
    getParentRoute: () => DashboardSchedulesRouteRoute,
  } as any)
const DashboardDronesDroneIdIndexRoute =
  DashboardDronesDroneIdIndexRouteImport.update({
    id: '/$droneId/',
    path: '/$droneId/',
    getParentRoute: () => DashboardDronesRouteRoute,
  } as any)
const DashboardSitesSiteIdEditRoute =
  DashboardSitesSiteIdEditRouteImport.update({
    id: '/$siteId/edit',
    path: '/$siteId/edit',
    getParentRoute: () => DashboardSitesRouteRoute,
  } as any)
const DashboardSchedulesScheduleIdEditRoute =
  DashboardSchedulesScheduleIdEditRouteImport.update({
    id: '/$scheduleId/edit',
    path: '/$scheduleId/edit',
    getParentRoute: () => DashboardSchedulesRouteRoute,
  } as any)
const DashboardJobsJobIdEditRoute = DashboardJobsJobIdEditRouteImport.update({
  id: '/$jobId/edit',
  path: '/$jobId/edit',
  getParentRoute: () => DashboardJobsRouteRoute,
} as any)
const DashboardDronesDroneIdEditRoute =
  DashboardDronesDroneIdEditRouteImport.update({
    id: '/$droneId/edit',
    path: '/$droneId/edit',
    getParentRoute: () => DashboardDronesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/drones': typeof DashboardDronesRouteRouteWithChildren
  '/dashboard/jobs': typeof DashboardJobsRouteRouteWithChildren
  '/dashboard/schedules': typeof DashboardSchedulesRouteRouteWithChildren
  '/dashboard/sites': typeof DashboardSitesRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/drones/new': typeof DashboardDronesNewRoute
  '/dashboard/forms/$formId': typeof DashboardFormsFormIdRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/schedules/new': typeof DashboardSchedulesNewRoute
  '/dashboard/sites/new': typeof DashboardSitesNewRoute
  '/dashboard/drones/': typeof DashboardDronesIndexRoute
  '/dashboard/forms/': typeof DashboardFormsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/schedules/': typeof DashboardSchedulesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sites/': typeof DashboardSitesIndexRoute
  '/dashboard/ui/': typeof DashboardUiIndexRoute
  '/dashboard/drones/$droneId/edit': typeof DashboardDronesDroneIdEditRoute
  '/dashboard/jobs/$jobId/edit': typeof DashboardJobsJobIdEditRoute
  '/dashboard/schedules/$scheduleId/edit': typeof DashboardSchedulesScheduleIdEditRoute
  '/dashboard/sites/$siteId/edit': typeof DashboardSitesSiteIdEditRoute
  '/dashboard/drones/$droneId/': typeof DashboardDronesDroneIdIndexRoute
  '/dashboard/schedules/$scheduleId/': typeof DashboardSchedulesScheduleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/drones/new': typeof DashboardDronesNewRoute
  '/dashboard/forms/$formId': typeof DashboardFormsFormIdRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/schedules/new': typeof DashboardSchedulesNewRoute
  '/dashboard/sites/new': typeof DashboardSitesNewRoute
  '/dashboard/drones': typeof DashboardDronesIndexRoute
  '/dashboard/forms': typeof DashboardFormsIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/schedules': typeof DashboardSchedulesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/sites': typeof DashboardSitesIndexRoute
  '/dashboard/ui': typeof DashboardUiIndexRoute
  '/dashboard/drones/$droneId/edit': typeof DashboardDronesDroneIdEditRoute
  '/dashboard/jobs/$jobId/edit': typeof DashboardJobsJobIdEditRoute
  '/dashboard/schedules/$scheduleId/edit': typeof DashboardSchedulesScheduleIdEditRoute
  '/dashboard/sites/$siteId/edit': typeof DashboardSitesSiteIdEditRoute
  '/dashboard/drones/$droneId': typeof DashboardDronesDroneIdIndexRoute
  '/dashboard/schedules/$scheduleId': typeof DashboardSchedulesScheduleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/drones': typeof DashboardDronesRouteRouteWithChildren
  '/dashboard/jobs': typeof DashboardJobsRouteRouteWithChildren
  '/dashboard/schedules': typeof DashboardSchedulesRouteRouteWithChildren
  '/dashboard/sites': typeof DashboardSitesRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/drones/new': typeof DashboardDronesNewRoute
  '/dashboard/forms/$formId': typeof DashboardFormsFormIdRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/schedules/new': typeof DashboardSchedulesNewRoute
  '/dashboard/sites/new': typeof DashboardSitesNewRoute
  '/dashboard/drones/': typeof DashboardDronesIndexRoute
  '/dashboard/forms/': typeof DashboardFormsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/schedules/': typeof DashboardSchedulesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sites/': typeof DashboardSitesIndexRoute
  '/dashboard/ui/': typeof DashboardUiIndexRoute
  '/dashboard/drones/$droneId/edit': typeof DashboardDronesDroneIdEditRoute
  '/dashboard/jobs/$jobId/edit': typeof DashboardJobsJobIdEditRoute
  '/dashboard/schedules/$scheduleId/edit': typeof DashboardSchedulesScheduleIdEditRoute
  '/dashboard/sites/$siteId/edit': typeof DashboardSitesSiteIdEditRoute
  '/dashboard/drones/$droneId/': typeof DashboardDronesDroneIdIndexRoute
  '/dashboard/schedules/$scheduleId/': typeof DashboardSchedulesScheduleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/drones'
    | '/dashboard/jobs'
    | '/dashboard/schedules'
    | '/dashboard/sites'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/drones/new'
    | '/dashboard/forms/$formId'
    | '/dashboard/jobs/new'
    | '/dashboard/schedules/new'
    | '/dashboard/sites/new'
    | '/dashboard/drones/'
    | '/dashboard/forms/'
    | '/dashboard/jobs/'
    | '/dashboard/schedules/'
    | '/dashboard/settings/'
    | '/dashboard/sites/'
    | '/dashboard/ui/'
    | '/dashboard/drones/$droneId/edit'
    | '/dashboard/jobs/$jobId/edit'
    | '/dashboard/schedules/$scheduleId/edit'
    | '/dashboard/sites/$siteId/edit'
    | '/dashboard/drones/$droneId/'
    | '/dashboard/schedules/$scheduleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/drones/new'
    | '/dashboard/forms/$formId'
    | '/dashboard/jobs/new'
    | '/dashboard/schedules/new'
    | '/dashboard/sites/new'
    | '/dashboard/drones'
    | '/dashboard/forms'
    | '/dashboard/jobs'
    | '/dashboard/schedules'
    | '/dashboard/settings'
    | '/dashboard/sites'
    | '/dashboard/ui'
    | '/dashboard/drones/$droneId/edit'
    | '/dashboard/jobs/$jobId/edit'
    | '/dashboard/schedules/$scheduleId/edit'
    | '/dashboard/sites/$siteId/edit'
    | '/dashboard/drones/$droneId'
    | '/dashboard/schedules/$scheduleId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/drones'
    | '/dashboard/jobs'
    | '/dashboard/schedules'
    | '/dashboard/sites'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/drones/new'
    | '/dashboard/forms/$formId'
    | '/dashboard/jobs/new'
    | '/dashboard/schedules/new'
    | '/dashboard/sites/new'
    | '/dashboard/drones/'
    | '/dashboard/forms/'
    | '/dashboard/jobs/'
    | '/dashboard/schedules/'
    | '/dashboard/settings/'
    | '/dashboard/sites/'
    | '/dashboard/ui/'
    | '/dashboard/drones/$droneId/edit'
    | '/dashboard/jobs/$jobId/edit'
    | '/dashboard/schedules/$scheduleId/edit'
    | '/dashboard/sites/$siteId/edit'
    | '/dashboard/drones/$droneId/'
    | '/dashboard/schedules/$scheduleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sites': {
      id: '/dashboard/sites'
      path: '/sites'
      fullPath: '/dashboard/sites'
      preLoaderRoute: typeof DashboardSitesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedules': {
      id: '/dashboard/schedules'
      path: '/schedules'
      fullPath: '/dashboard/schedules'
      preLoaderRoute: typeof DashboardSchedulesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs': {
      id: '/dashboard/jobs'
      path: '/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof DashboardJobsRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/drones': {
      id: '/dashboard/drones'
      path: '/drones'
      fullPath: '/dashboard/drones'
      preLoaderRoute: typeof DashboardDronesRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ui/': {
      id: '/dashboard/ui/'
      path: '/ui'
      fullPath: '/dashboard/ui/'
      preLoaderRoute: typeof DashboardUiIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sites/': {
      id: '/dashboard/sites/'
      path: '/'
      fullPath: '/dashboard/sites/'
      preLoaderRoute: typeof DashboardSitesIndexRouteImport
      parentRoute: typeof DashboardSitesRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedules/': {
      id: '/dashboard/schedules/'
      path: '/'
      fullPath: '/dashboard/schedules/'
      preLoaderRoute: typeof DashboardSchedulesIndexRouteImport
      parentRoute: typeof DashboardSchedulesRouteRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardJobsRouteRoute
    }
    '/dashboard/forms/': {
      id: '/dashboard/forms/'
      path: '/forms'
      fullPath: '/dashboard/forms/'
      preLoaderRoute: typeof DashboardFormsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/drones/': {
      id: '/dashboard/drones/'
      path: '/'
      fullPath: '/dashboard/drones/'
      preLoaderRoute: typeof DashboardDronesIndexRouteImport
      parentRoute: typeof DashboardDronesRouteRoute
    }
    '/dashboard/sites/new': {
      id: '/dashboard/sites/new'
      path: '/new'
      fullPath: '/dashboard/sites/new'
      preLoaderRoute: typeof DashboardSitesNewRouteImport
      parentRoute: typeof DashboardSitesRouteRoute
    }
    '/dashboard/schedules/new': {
      id: '/dashboard/schedules/new'
      path: '/new'
      fullPath: '/dashboard/schedules/new'
      preLoaderRoute: typeof DashboardSchedulesNewRouteImport
      parentRoute: typeof DashboardSchedulesRouteRoute
    }
    '/dashboard/jobs/new': {
      id: '/dashboard/jobs/new'
      path: '/new'
      fullPath: '/dashboard/jobs/new'
      preLoaderRoute: typeof DashboardJobsNewRouteImport
      parentRoute: typeof DashboardJobsRouteRoute
    }
    '/dashboard/forms/$formId': {
      id: '/dashboard/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/dashboard/forms/$formId'
      preLoaderRoute: typeof DashboardFormsFormIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/drones/new': {
      id: '/dashboard/drones/new'
      path: '/new'
      fullPath: '/dashboard/drones/new'
      preLoaderRoute: typeof DashboardDronesNewRouteImport
      parentRoute: typeof DashboardDronesRouteRoute
    }
    '/dashboard/schedules/$scheduleId/': {
      id: '/dashboard/schedules/$scheduleId/'
      path: '/$scheduleId'
      fullPath: '/dashboard/schedules/$scheduleId/'
      preLoaderRoute: typeof DashboardSchedulesScheduleIdIndexRouteImport
      parentRoute: typeof DashboardSchedulesRouteRoute
    }
    '/dashboard/drones/$droneId/': {
      id: '/dashboard/drones/$droneId/'
      path: '/$droneId'
      fullPath: '/dashboard/drones/$droneId/'
      preLoaderRoute: typeof DashboardDronesDroneIdIndexRouteImport
      parentRoute: typeof DashboardDronesRouteRoute
    }
    '/dashboard/sites/$siteId/edit': {
      id: '/dashboard/sites/$siteId/edit'
      path: '/$siteId/edit'
      fullPath: '/dashboard/sites/$siteId/edit'
      preLoaderRoute: typeof DashboardSitesSiteIdEditRouteImport
      parentRoute: typeof DashboardSitesRouteRoute
    }
    '/dashboard/schedules/$scheduleId/edit': {
      id: '/dashboard/schedules/$scheduleId/edit'
      path: '/$scheduleId/edit'
      fullPath: '/dashboard/schedules/$scheduleId/edit'
      preLoaderRoute: typeof DashboardSchedulesScheduleIdEditRouteImport
      parentRoute: typeof DashboardSchedulesRouteRoute
    }
    '/dashboard/jobs/$jobId/edit': {
      id: '/dashboard/jobs/$jobId/edit'
      path: '/$jobId/edit'
      fullPath: '/dashboard/jobs/$jobId/edit'
      preLoaderRoute: typeof DashboardJobsJobIdEditRouteImport
      parentRoute: typeof DashboardJobsRouteRoute
    }
    '/dashboard/drones/$droneId/edit': {
      id: '/dashboard/drones/$droneId/edit'
      path: '/$droneId/edit'
      fullPath: '/dashboard/drones/$droneId/edit'
      preLoaderRoute: typeof DashboardDronesDroneIdEditRouteImport
      parentRoute: typeof DashboardDronesRouteRoute
    }
  }
}

interface DashboardDronesRouteRouteChildren {
  DashboardDronesNewRoute: typeof DashboardDronesNewRoute
  DashboardDronesIndexRoute: typeof DashboardDronesIndexRoute
  DashboardDronesDroneIdEditRoute: typeof DashboardDronesDroneIdEditRoute
  DashboardDronesDroneIdIndexRoute: typeof DashboardDronesDroneIdIndexRoute
}

const DashboardDronesRouteRouteChildren: DashboardDronesRouteRouteChildren = {
  DashboardDronesNewRoute: DashboardDronesNewRoute,
  DashboardDronesIndexRoute: DashboardDronesIndexRoute,
  DashboardDronesDroneIdEditRoute: DashboardDronesDroneIdEditRoute,
  DashboardDronesDroneIdIndexRoute: DashboardDronesDroneIdIndexRoute,
}

const DashboardDronesRouteRouteWithChildren =
  DashboardDronesRouteRoute._addFileChildren(DashboardDronesRouteRouteChildren)

interface DashboardJobsRouteRouteChildren {
  DashboardJobsNewRoute: typeof DashboardJobsNewRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardJobsJobIdEditRoute: typeof DashboardJobsJobIdEditRoute
}

const DashboardJobsRouteRouteChildren: DashboardJobsRouteRouteChildren = {
  DashboardJobsNewRoute: DashboardJobsNewRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardJobsJobIdEditRoute: DashboardJobsJobIdEditRoute,
}

const DashboardJobsRouteRouteWithChildren =
  DashboardJobsRouteRoute._addFileChildren(DashboardJobsRouteRouteChildren)

interface DashboardSchedulesRouteRouteChildren {
  DashboardSchedulesNewRoute: typeof DashboardSchedulesNewRoute
  DashboardSchedulesIndexRoute: typeof DashboardSchedulesIndexRoute
  DashboardSchedulesScheduleIdEditRoute: typeof DashboardSchedulesScheduleIdEditRoute
  DashboardSchedulesScheduleIdIndexRoute: typeof DashboardSchedulesScheduleIdIndexRoute
}

const DashboardSchedulesRouteRouteChildren: DashboardSchedulesRouteRouteChildren =
  {
    DashboardSchedulesNewRoute: DashboardSchedulesNewRoute,
    DashboardSchedulesIndexRoute: DashboardSchedulesIndexRoute,
    DashboardSchedulesScheduleIdEditRoute:
      DashboardSchedulesScheduleIdEditRoute,
    DashboardSchedulesScheduleIdIndexRoute:
      DashboardSchedulesScheduleIdIndexRoute,
  }

const DashboardSchedulesRouteRouteWithChildren =
  DashboardSchedulesRouteRoute._addFileChildren(
    DashboardSchedulesRouteRouteChildren,
  )

interface DashboardSitesRouteRouteChildren {
  DashboardSitesNewRoute: typeof DashboardSitesNewRoute
  DashboardSitesIndexRoute: typeof DashboardSitesIndexRoute
  DashboardSitesSiteIdEditRoute: typeof DashboardSitesSiteIdEditRoute
}

const DashboardSitesRouteRouteChildren: DashboardSitesRouteRouteChildren = {
  DashboardSitesNewRoute: DashboardSitesNewRoute,
  DashboardSitesIndexRoute: DashboardSitesIndexRoute,
  DashboardSitesSiteIdEditRoute: DashboardSitesSiteIdEditRoute,
}

const DashboardSitesRouteRouteWithChildren =
  DashboardSitesRouteRoute._addFileChildren(DashboardSitesRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardDronesRouteRoute: typeof DashboardDronesRouteRouteWithChildren
  DashboardJobsRouteRoute: typeof DashboardJobsRouteRouteWithChildren
  DashboardSchedulesRouteRoute: typeof DashboardSchedulesRouteRouteWithChildren
  DashboardSitesRouteRoute: typeof DashboardSitesRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFormsFormIdRoute: typeof DashboardFormsFormIdRoute
  DashboardFormsIndexRoute: typeof DashboardFormsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardUiIndexRoute: typeof DashboardUiIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDronesRouteRoute: DashboardDronesRouteRouteWithChildren,
  DashboardJobsRouteRoute: DashboardJobsRouteRouteWithChildren,
  DashboardSchedulesRouteRoute: DashboardSchedulesRouteRouteWithChildren,
  DashboardSitesRouteRoute: DashboardSitesRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFormsFormIdRoute: DashboardFormsFormIdRoute,
  DashboardFormsIndexRoute: DashboardFormsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardUiIndexRoute: DashboardUiIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
