/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardSitesIndexRouteImport } from './routes/dashboard/sites/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSchedulesIndexRouteImport } from './routes/dashboard/schedules/index'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard/jobs/index'
import { Route as DashboardFormsIndexRouteImport } from './routes/dashboard/forms/index'
import { Route as DashboardDronesIndexRouteImport } from './routes/dashboard/drones/index'
import { Route as DashboardSitesNewRouteImport } from './routes/dashboard/sites/new'
import { Route as DashboardSchedulesNewRouteImport } from './routes/dashboard/schedules/new'
import { Route as DashboardJobsNewRouteImport } from './routes/dashboard/jobs/new'
import { Route as DashboardFormsFormIdRouteImport } from './routes/dashboard/forms/$formId'
import { Route as DashboardSchedulesScheduleIdIndexRouteImport } from './routes/dashboard/schedules/$scheduleId/index'
import { Route as DashboardSitesSiteIdEditRouteImport } from './routes/dashboard/sites/$siteId/edit'
import { Route as DashboardSchedulesScheduleIdEditRouteImport } from './routes/dashboard/schedules/$scheduleId/edit'
import { Route as DashboardJobsJobIdEditRouteImport } from './routes/dashboard/jobs/$jobId/edit'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSitesIndexRoute = DashboardSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchedulesIndexRoute = DashboardSchedulesIndexRouteImport.update({
  id: '/schedules/',
  path: '/schedules/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFormsIndexRoute = DashboardFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDronesIndexRoute = DashboardDronesIndexRouteImport.update({
  id: '/drones/',
  path: '/drones/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSitesNewRoute = DashboardSitesNewRouteImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchedulesNewRoute = DashboardSchedulesNewRouteImport.update({
  id: '/schedules/new',
  path: '/schedules/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobsNewRoute = DashboardJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFormsFormIdRoute = DashboardFormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSchedulesScheduleIdIndexRoute =
  DashboardSchedulesScheduleIdIndexRouteImport.update({
    id: '/schedules/$scheduleId/',
    path: '/schedules/$scheduleId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSitesSiteIdEditRoute =
  DashboardSitesSiteIdEditRouteImport.update({
    id: '/sites/$siteId/edit',
    path: '/sites/$siteId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSchedulesScheduleIdEditRoute =
  DashboardSchedulesScheduleIdEditRouteImport.update({
    id: '/schedules/$scheduleId/edit',
    path: '/schedules/$scheduleId/edit',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardJobsJobIdEditRoute = DashboardJobsJobIdEditRouteImport.update({
  id: '/jobs/$jobId/edit',
  path: '/jobs/$jobId/edit',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/forms/$formId': typeof DashboardFormsFormIdRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/schedules/new': typeof DashboardSchedulesNewRoute
  '/dashboard/sites/new': typeof DashboardSitesNewRoute
  '/dashboard/drones/': typeof DashboardDronesIndexRoute
  '/dashboard/forms/': typeof DashboardFormsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/schedules/': typeof DashboardSchedulesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sites/': typeof DashboardSitesIndexRoute
  '/dashboard/jobs/$jobId/edit': typeof DashboardJobsJobIdEditRoute
  '/dashboard/schedules/$scheduleId/edit': typeof DashboardSchedulesScheduleIdEditRoute
  '/dashboard/sites/$siteId/edit': typeof DashboardSitesSiteIdEditRoute
  '/dashboard/schedules/$scheduleId/': typeof DashboardSchedulesScheduleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/forms/$formId': typeof DashboardFormsFormIdRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/schedules/new': typeof DashboardSchedulesNewRoute
  '/dashboard/sites/new': typeof DashboardSitesNewRoute
  '/dashboard/drones': typeof DashboardDronesIndexRoute
  '/dashboard/forms': typeof DashboardFormsIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/schedules': typeof DashboardSchedulesIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/sites': typeof DashboardSitesIndexRoute
  '/dashboard/jobs/$jobId/edit': typeof DashboardJobsJobIdEditRoute
  '/dashboard/schedules/$scheduleId/edit': typeof DashboardSchedulesScheduleIdEditRoute
  '/dashboard/sites/$siteId/edit': typeof DashboardSitesSiteIdEditRoute
  '/dashboard/schedules/$scheduleId': typeof DashboardSchedulesScheduleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/forms/$formId': typeof DashboardFormsFormIdRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/schedules/new': typeof DashboardSchedulesNewRoute
  '/dashboard/sites/new': typeof DashboardSitesNewRoute
  '/dashboard/drones/': typeof DashboardDronesIndexRoute
  '/dashboard/forms/': typeof DashboardFormsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/schedules/': typeof DashboardSchedulesIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/sites/': typeof DashboardSitesIndexRoute
  '/dashboard/jobs/$jobId/edit': typeof DashboardJobsJobIdEditRoute
  '/dashboard/schedules/$scheduleId/edit': typeof DashboardSchedulesScheduleIdEditRoute
  '/dashboard/sites/$siteId/edit': typeof DashboardSitesSiteIdEditRoute
  '/dashboard/schedules/$scheduleId/': typeof DashboardSchedulesScheduleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/forms/$formId'
    | '/dashboard/jobs/new'
    | '/dashboard/schedules/new'
    | '/dashboard/sites/new'
    | '/dashboard/drones/'
    | '/dashboard/forms/'
    | '/dashboard/jobs/'
    | '/dashboard/schedules/'
    | '/dashboard/settings/'
    | '/dashboard/sites/'
    | '/dashboard/jobs/$jobId/edit'
    | '/dashboard/schedules/$scheduleId/edit'
    | '/dashboard/sites/$siteId/edit'
    | '/dashboard/schedules/$scheduleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/forms/$formId'
    | '/dashboard/jobs/new'
    | '/dashboard/schedules/new'
    | '/dashboard/sites/new'
    | '/dashboard/drones'
    | '/dashboard/forms'
    | '/dashboard/jobs'
    | '/dashboard/schedules'
    | '/dashboard/settings'
    | '/dashboard/sites'
    | '/dashboard/jobs/$jobId/edit'
    | '/dashboard/schedules/$scheduleId/edit'
    | '/dashboard/sites/$siteId/edit'
    | '/dashboard/schedules/$scheduleId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/forms/$formId'
    | '/dashboard/jobs/new'
    | '/dashboard/schedules/new'
    | '/dashboard/sites/new'
    | '/dashboard/drones/'
    | '/dashboard/forms/'
    | '/dashboard/jobs/'
    | '/dashboard/schedules/'
    | '/dashboard/settings/'
    | '/dashboard/sites/'
    | '/dashboard/jobs/$jobId/edit'
    | '/dashboard/schedules/$scheduleId/edit'
    | '/dashboard/sites/$siteId/edit'
    | '/dashboard/schedules/$scheduleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sites/': {
      id: '/dashboard/sites/'
      path: '/sites'
      fullPath: '/dashboard/sites/'
      preLoaderRoute: typeof DashboardSitesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedules/': {
      id: '/dashboard/schedules/'
      path: '/schedules'
      fullPath: '/dashboard/schedules/'
      preLoaderRoute: typeof DashboardSchedulesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/jobs'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/forms/': {
      id: '/dashboard/forms/'
      path: '/forms'
      fullPath: '/dashboard/forms/'
      preLoaderRoute: typeof DashboardFormsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/drones/': {
      id: '/dashboard/drones/'
      path: '/drones'
      fullPath: '/dashboard/drones/'
      preLoaderRoute: typeof DashboardDronesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sites/new': {
      id: '/dashboard/sites/new'
      path: '/sites/new'
      fullPath: '/dashboard/sites/new'
      preLoaderRoute: typeof DashboardSitesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedules/new': {
      id: '/dashboard/schedules/new'
      path: '/schedules/new'
      fullPath: '/dashboard/schedules/new'
      preLoaderRoute: typeof DashboardSchedulesNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/new': {
      id: '/dashboard/jobs/new'
      path: '/jobs/new'
      fullPath: '/dashboard/jobs/new'
      preLoaderRoute: typeof DashboardJobsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/forms/$formId': {
      id: '/dashboard/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/dashboard/forms/$formId'
      preLoaderRoute: typeof DashboardFormsFormIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedules/$scheduleId/': {
      id: '/dashboard/schedules/$scheduleId/'
      path: '/schedules/$scheduleId'
      fullPath: '/dashboard/schedules/$scheduleId/'
      preLoaderRoute: typeof DashboardSchedulesScheduleIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/sites/$siteId/edit': {
      id: '/dashboard/sites/$siteId/edit'
      path: '/sites/$siteId/edit'
      fullPath: '/dashboard/sites/$siteId/edit'
      preLoaderRoute: typeof DashboardSitesSiteIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/schedules/$scheduleId/edit': {
      id: '/dashboard/schedules/$scheduleId/edit'
      path: '/schedules/$scheduleId/edit'
      fullPath: '/dashboard/schedules/$scheduleId/edit'
      preLoaderRoute: typeof DashboardSchedulesScheduleIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/jobs/$jobId/edit': {
      id: '/dashboard/jobs/$jobId/edit'
      path: '/jobs/$jobId/edit'
      fullPath: '/dashboard/jobs/$jobId/edit'
      preLoaderRoute: typeof DashboardJobsJobIdEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFormsFormIdRoute: typeof DashboardFormsFormIdRoute
  DashboardJobsNewRoute: typeof DashboardJobsNewRoute
  DashboardSchedulesNewRoute: typeof DashboardSchedulesNewRoute
  DashboardSitesNewRoute: typeof DashboardSitesNewRoute
  DashboardDronesIndexRoute: typeof DashboardDronesIndexRoute
  DashboardFormsIndexRoute: typeof DashboardFormsIndexRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardSchedulesIndexRoute: typeof DashboardSchedulesIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardSitesIndexRoute: typeof DashboardSitesIndexRoute
  DashboardJobsJobIdEditRoute: typeof DashboardJobsJobIdEditRoute
  DashboardSchedulesScheduleIdEditRoute: typeof DashboardSchedulesScheduleIdEditRoute
  DashboardSitesSiteIdEditRoute: typeof DashboardSitesSiteIdEditRoute
  DashboardSchedulesScheduleIdIndexRoute: typeof DashboardSchedulesScheduleIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFormsFormIdRoute: DashboardFormsFormIdRoute,
  DashboardJobsNewRoute: DashboardJobsNewRoute,
  DashboardSchedulesNewRoute: DashboardSchedulesNewRoute,
  DashboardSitesNewRoute: DashboardSitesNewRoute,
  DashboardDronesIndexRoute: DashboardDronesIndexRoute,
  DashboardFormsIndexRoute: DashboardFormsIndexRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardSchedulesIndexRoute: DashboardSchedulesIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardSitesIndexRoute: DashboardSitesIndexRoute,
  DashboardJobsJobIdEditRoute: DashboardJobsJobIdEditRoute,
  DashboardSchedulesScheduleIdEditRoute: DashboardSchedulesScheduleIdEditRoute,
  DashboardSitesSiteIdEditRoute: DashboardSitesSiteIdEditRoute,
  DashboardSchedulesScheduleIdIndexRoute:
    DashboardSchedulesScheduleIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
